name: Turtle_Classifier
channels:
  - conda
  - conda-forge
  - pytorch
dependencies:
  - python=3.7.9
  - voila
  - pip
  - jupyter-server-proxy
  - pytorch 
  - torchvision
  - pip:        
    - fastai==2.0.10 
